### ISSUE TITLE
[FEAT] Allow users to configure pre-installed Linux libraries

### ISSUE THREAD

**Issue by Coopyrightdmin** [Alien6-Studio/outerspace-apizr#9]
### Problem Statement

Currently, users do not have the capability to configure which Linux libraries should be pre-installed. This limitation may hinder the container's adaptability for specific requirements.

### Benefits

Allowing users to select which Linux libraries to pre-install would:
- Offer greater flexibility to tailor the container to specific needs.
- Reduce post-installation configuration time.
- Enhance the user experience by providing deeper control over the container setup.

### Additional context

Many users have specific requirements that demand certain Linux libraries. This feature would enable them to produce a ready-to-use container without the need to manually install these libraries post-container creation.

### Priority/Severity

- [ ] High (This will bring a huge increase in performance/productivity/usability/legislative cover)
- [x] Medium (This will bring a good increase in performance/productivity/usability)
- [ ] Low (anything else e.g., trivial, minor improvements)

**Comment by Coopyrightdmin** [comment]
We've extended the configuration to allow users to specify both Linux libraries associated with specific Python packages and custom packages independent of any Python dependencies. Here's a brief overview of the YAML structure:

```yaml
dependencies:
  - name: numpy
    packages:
      - gcc
      - g++
      - musl-dev
      - python3-dev
      - gfortran
  - name: scikit_learn
    packages:
      - gcc
      - g++
      - musl-dev
      - python3-dev
      - gfortran
      - openblas-dev
      - lapack-dev
custom_packages:
  - libjpeg
  - imagemagick
  - jq
```

This update provides users with a more flexible and customizable container setup experience, allowing them to specify both Python-related and independent Linux packages.
